### PR TITLE
Fix: Tiva-C/Stelaris device probing issues

### LINKED ISSUE #958: Errors using SWD while trying to erase blocks on a Tiva-C target
Using the latest source for BMP, we get the following errors with a native BMP over SWD when trying to erase blocks on a target (TM4C123GH6PM) but not over JTAG:

```
❯ src/blackmagic -E 0x2000
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40000ff8
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40043200
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40048024
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x4004804c
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x400e0940
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x400e0740
❯ src/blackmagic -j -E 0x2000
❯ 
```

Additionally, if this is immediately followed by an info dump over SWD the following additional errors are generated:

```
❯ src/blackmagic -t
INFO: Open USB 046d:082d class ef failed
BMP hosted v1.7.1-243-g9cfc854-dirty
 for ST-Link V2/3, CMSIS_DAP, JLINK and LIBFTDI/MPSSE
Using 1d50:6018 8BB209F2 Black Sphere Technologies
 Black Magic Probe  c50f317-dirty
Running in Test Mode
Target voltage: 3.3V Volt
Speed set to  3.2727 MHz for SWD
Exception: SWDP invalid ACK
Trying old JTAG to SWD sequence
DPIDR 0x2ba01477 (v1 rev2)
RESET_SEQ failed
AP   0: IDR=24770011 CFG=00000000 BASE=e00ff003 CSW=23000040 (AHB-AP var1 rev2
Halt via DHCSR: success 00030003 after 1ms
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer 43b Partno 4c4
0 0xe000e000: Generic IP component - Cortex-M4 SCS (System Control Space) (PIDR = 0x04000bb00c  DEVTYPE = 0x00 ARCHID = 0x0000)-> cortexm_probe
CPUID 0x410fc241 (M4 var 0 rev 1)
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40000ff8
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40043200
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x40048024
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x4004804c
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x400e0940
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 0, addr: 0x400e0740
1 0xe0001000: Generic IP component - Cortex-M3 DWT (Data Watchpoint and Trace) (PIDR = 0x04003bb002  DEVTYPE = 0x00 ARCHID = 0x0000)
2 0xe0002000: Generic IP component - Cortex-M3 FBP (Flash Patch and Breakpoint) (PIDR = 0x04002bb003  DEVTYPE = 0x00 ARCHID = 0x0000)
3 0xe0000000: Generic IP component - Cortex-M3 ITM (Instrumentation Trace Module) (PIDR = 0x04003bb001  DEVTYPE = 0x00 ARCHID = 0x0000)
4 0xe0040000: Debug component - Cortex-M4 TPIU (Trace Port Interface Unit) (PIDR = 0x04000bb9a1  DEVTYPE = 0x11 ARCHID = 0x0000)
5 0xe0041000: Debug component - Cortex-M4 ETM (Embedded Trace) (PIDR = 0x04000bb925  DEVTYPE = 0x13 ARCHID = 0x0000)
ROM: Table END
***  1      TI Stellaris/Tiva M4
RAM   Start: 0x20000000 length = 0x10000
Flash Start: 0x00000000 length = 0x80000 blocksize 0x400
```

Except for "RESET_SEQ failed", the JTAG version of this cleanly runs and succeeds.

### PR DESCRIPTION
**Pull request by dragonmux**
In this PR we seek to address issues probing for TI Tiva-C and Stelaris devices which, because of where the probe routine is in the sequence, get put into a bad state and fail to scan under certain circumstances by the time the routine fires.

In addressing this we have inadvertantly ended up diving into the LM3S datasheets and adding support for a couple of new micros + fixing the Flash and RAM regions for another.

This fixes #958

### CODE REVIEW

File: src/target/adiv5.c [hunk 1]
```diff
@@ -586,10 +584,10 @@ static void adiv5_component_probe(ADIv5_AP_t *ap, uint32_t addr, const size_t re
 				arm_component_lut[i].arch_id != arch_id)
 				continue;
 
-			DEBUG_INFO("%s%d 0x%" PRIx32 ": %s - %s %s (PIDR = 0x%02" PRIx32 "%08" PRIx32 "  DEVTYPE = 0x%02" PRIx8
+			DEBUG_INFO("%s%d 0x%" PRIx32 ": %s - %s %s (PIDR = 0x%016" PRIx64 "  DEVTYPE = 0x%02" PRIx8
```
Comment (perigoso) [inline src/target/adiv5.c:587]: Doesn't newlib not support > 32 bit variables on printf? Or is this hosted only code (on mobile, hard to see context)

Comment (dragonmux) [reply src/target/adiv5.c:587]: Good question.. we'll revert this particular change if it doesn't, we'll test a debug build of this PR in the morning to check

Comment (dragonmux) [reply src/target/adiv5.c:587]: This bothered us enough that we actually already checked and you're correct, newlib doesn't support 64-bit printf 😞 and people wonder why we roll our own when we have a choice

**Review by esden — APPROVED** [review]
LGTM
