### PR TITLE
hosted: fix ephemeral max frequency

### LINKED ISSUE #1691: BMDA probe frequency is ephemeral
On BMDA, the scan routines set the interface frequencies according to command line options, always, meaning any changes by the user through monitor commands are overriden.

``` c
bool bmda_swd_scan(const uint32_t targetid)
{
	bmda_probe_info.is_jtag = false;
	platform_max_frequency_set(cl_opts.opt_max_swj_frequency); <-------

	switch (bmda_probe_info.type) {
	case PROBE_TYPE_BMP:
	case PROBE_TYPE_FTDI:
	case PROBE_TYPE_CMSIS_DAP:
	case PROBE_TYPE_JLINK:
		return adiv5_swd_scan(targetid);

#if HOSTED_BMP_ONLY == 0
	case PROBE_TYPE_STLINK_V2:
		return stlink_swd_scan();
#endif

	default:
		return false;
	}
}
```

``` c
bool bmda_jtag_scan(void)
{
	bmda_probe_info.is_jtag = true;

	platform_max_frequency_set(cl_opts.opt_max_swj_frequency); <-------

	switch (bmda_probe_info.type) {
	case PROBE_TYPE_BMP:
	case PROBE_TYPE_FTDI:
	case PROBE_TYPE_JLINK:
	case PROBE_TYPE_CMSIS_DAP:
		return jtag_scan();

#if HOSTED_BMP_ONLY == 0
	case PROBE_TYPE_STLINK_V2:
		return stlink_jtag_scan();
#endif

	default:
		return false;
	}
}
```

Example:
setting SWD frequency with `mon freq 400000`
immediately followed by a scan `mon swd`
```
Speed set to 0.400MHz for SWD
Speed set to 1.600MHz for SWD
-> jlink_swd_init(0)
Switching out of dormant state into SWD
jlink_swd_seq_out 32 clock_cycles: ffffffff

...

```

### PR DESCRIPTION
**Pull request by perigoso**
## Detailed description

On BMDA, the scan routines set the interface frequencies according to command line options, always, meaning any changes by the user through monitor commands are overriden. This fixes that, this is a rather simplistic fix, that *just* resolves the issue, there is space for improvement on this code generally, but that would be more involved and can be done later.

This adds storage to the max frequency, meaning the frequency set by the user will be remembered over the initial command line value.

Before:

setting SWD frequency with mon freq 400000
immediately followed by a scan mon swd
```
Speed set to 0.400MHz for SWD
Speed set to 1.600MHz for SWD
-> jlink_swd_init(0)
Switching out of dormant state into SWD
jlink_swd_seq_out 32 clock_cycles: ffffffff

...
```
After:
setting SWD frequency with mon freq 400000
immediately followed by a scan mon swd
```
Speed set to 0.400MHz for SWD
Speed set to 0.400MHz for SWD
-> jlink_swd_init(0)
Switching out of dormant state into SWD
jlink_swd_seq_out 32 clock_cycles: ffffffff

...
```

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [ ] ~~It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))~~
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

fixes #1691

### CODE REVIEW

File: src/command.c [hunk 1]
```diff
@@ -360,9 +360,9 @@ bool cmd_frequency(target_s *t, int argc, const char **argv)
 	}
 	const uint32_t freq = platform_max_frequency_get();
 	if (freq == FREQ_FIXED)
-		gdb_outf("SWJ freq fixed\n");
+		gdb_outf("Debug interface frequency is not configurable.\n");
```
Comment (dragonmux) [inline src/command.c:363]: Given this does get built into the firmware, perhaps `"Debug iface frequency is fixed\n"`? Just to try and conserve a few characters - we like the change otherwise and perhaps it might be worth `#if`'ing this and a shorter string on `PC_HOSTED == 1`.

File: src/platforms/hosted/platform.c [hunk 2]
```diff
@@ -442,14 +450,15 @@ void platform_max_frequency_set(uint32_t freq)
 #endif
 
 	default:
-		DEBUG_WARN("Setting max SWD/JTAG frequency not yet implemented\n");
+		DEBUG_WARN("Setting max %s frequency not available or not yet implemented\n",
```
Comment (dragonmux) [inline src/platforms/hosted/platform.c:453]: Perhaps "debug interface" here instead of "SWD/JTAG"? for more consistent nomenclature through out..

This works though given the rest of the code below. We much appreciate this getting rid of some more use of "SWJ" which goes totally unexplained in the rest of the code base otherwise.

**Review by dragonmux — COMMENTED** [review]
There are a couple of wording items we'd like to discuss that may need some change, but otherwise this looks great.

**Review by dragonmux — APPROVED** [review]
LGTM, we'll test this tomorrow and get it merged once we have.
