### PR TITLE
Fix: Unable to detect non-conforming JTAG processors

### LINKED ISSUE #1130: Allow bypassing JTAG scan sanity checks
When scanning out IRs IEEE 1149.1 mandates that the first bit output be set to 1.
BMP verify this compliance and errors out should the devices in the chain not comply to IEEE 1149.1.
Sadly, some devices do not comply to the standard and include non-compliant devices in their chains.

### PR DESCRIPTION
**Pull request by dragonmux**
In this PR we address that some processors don't have conforming implementations of IEEE 1149.1 (JTAG) which prevents jtag_scan() from functioning correctly for them.

We relax the conformance checks to warnings, and address the state of the JTAG scan code, performing type fixes and nomenclature cleanup.

This has been tested against STM32F4, LPC3470, and TM4C.

This fixes #1130.

### CODE REVIEW

File: src/target/jtag_scan.c [hunk 1]
```diff
@@ -153,101 +160,106 @@ int jtag_scan(const uint8_t *irlens)
...
-	for(i = 0; i < jtag_dev_count; i++)
-		platform_add_jtag_dev(i, &jtag_devs[i]);
-	for(i = 0; i < jtag_dev_count; i++) {
-		DEBUG_INFO("Idcode 0x%08" PRIx32, jtag_devs[i].jd_idcode);
-		for(j = 0; dev_descr[j].idcode; j++) {
-			if((jtag_devs[i].jd_idcode & dev_descr[j].idmask) ==
-			   dev_descr[j].idcode) {
-				DEBUG_INFO(": %s",
-						  (dev_descr[j].descr) ? dev_descr[j].descr : "unknown");
+	/*Transfer needed device information to firmware jtag_devs */
```
Comment (ylm) [inline src/target/jtag_scan.c:202]: /* Transfer needed device information to firmware jtag_devs */

**Review by esden — APPROVED** [review]
LGTM, quickly tested on 1bitsy

For this kind of stuff we badly need our HITL CI :) But for now we have to :crossed_fingers: :D

**Comment by dragonmux** [comment]
Agreed with the HITL CI - soon™ :)
