### PR TITLE
Fix: Declare correct RAM sizes for STM32F7

### LINKED ISSUE #2006: [STM32F72x] Incorrect memory map
I tried debugging an STM32F722 with blackmagic probe, and it worked... until my code grew bigger.
I looked into the code, the memory region for both flash and RAM are incorrect.

# How to reproduce
- Place a breakpoint in a code located after 0x210000 (flash on ITCM interface)
- `set mem inaccessible-by-default off`
- Run code: the code does not stop at the breakpoint

# Solution

## RAM
It had no effect in my situation, but I replaced these two lines:
https://github.com/blackmagic-debug/blackmagic/blob/729b7730cf64b7dd46c8e472c0bc622051a48730/src/target/stm32f4.c#L425-L426
with
```
target_add_ram32(target, 0x20000000, 0x10000); /* 64kiB DTCM RAM */
target_add_ram32(target, 0x20010000, 0x30000); /* 192kiB RAM */
```

## Flash
And I made it work by replacing these 2 lines:
https://github.com/blackmagic-debug/blackmagic/blob/729b7730cf64b7dd46c8e472c0bc622051a48730/src/target/stm32f4.c#L477-L478
with
```
if (is_f7) {
    stm32f4_add_flash(target, ITCM_BASE, 0x10000, 0x4000, 0, split);
    stm32f4_add_flash(target, ITCM_BASE+0x10000, 0x10000, 0x10000, 4, split);
    stm32f4_add_flash(target, ITCM_BASE+0x20000, 0x60000, 0x20000, 5, split);
}
```

Which is exactly the code a few lines below, except the STM32F72xxx is not dual bank.
https://github.com/blackmagic-debug/blackmagic/blob/729b7730cf64b7dd46c8e472c0bc622051a48730/src/target/stm32f4.c#L486-L492

# Next steps
I am not confident in doing a pull request because of the intricate code paths.
If I had to do it, I would probably try to replace all the `if... else...` by an array of structures defining the memory map for each devices. I am not sure that this is the path you want to take, and maybe there are issues with this method I don't foresee, so I am leaving it to you to decide what to do.

### PR DESCRIPTION
**Pull request by ALTracer**
## Detailed description

* No new features.
* The existing problem is RTT Auto Search triggering lots of SWD Fault past end of physical SRAM on STM32F722.
* This PR solves it by shrinking declared memory map and dispatching datasheet values per-family.

As I've tried to inspect/debug a project on a board involving STM32F722, the RTT Auto Search feature (which is supposed to be plug&play without configuration) started scrubbing available RAM but fell off the 192 KiB cliff trying to scan all 384 KiB of AHB SRAM which should be present on STM32F777. Confirmed with `blackpill-f411ce` and BMDA. I know about `mon rtt mem` ranges but this sounds more like a workaround rather than fix, BMD should provide knowledge of DUT flash and RAM maps and sizes.

Note this was not rigorously tested with a real project yet. I don't like the seven function calls, this can be further reduced to three via stack locals, should be cheaper than a full LUT. Update: reduced, was +80, now is +48 bytes size-diff.
Tested on STM32F722RE to no longer generate "SWD access resulted in fault" messages during reads outside RAM bounds, and to create a smaller correct RAM map.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #2006.

### CODE REVIEW

**Comment by ALTracer** [comment]
Seven function calls costed more flash than two calls, so the #1710 approach is not optimal either.
Clarify whether I should also add the 8 datasheets and 3 reference manuals (RM0385, RM0410, RM0431) for STM32F7 to top of file.
I also have a minor fix for ITCM inconsistency for a follow-up PR, but it worsens `blank_check` behaviour (will check twice). Finally, I also will have a medium fix for STM32F4 RAM being pinned to `320kiB` which is too blanket, in another PR.

**Comment by dragonmux** [comment]
> Clarify whether I should also add the 8 datasheets and 3 reference manuals (RM0385, RM0410, RM0431) for STM32F7 to top of file.

It would be best if these are specified at the top of the files, yes please - means it's easier to find them again to look them up and get the references as needed for contributors.

File: src/target/stm32f4.c [hunk 1]
```diff
@@ -423,9 +423,21 @@ static bool stm32f4_attach(target_s *const target)
...
 	bool use_dual_bank = !is_f7 && dual_bank;
 	if (is_f7) {
-		target_add_ram32(target, 0x00000000, 0x4000);  /* 16kiB ITCM RAM */
-		target_add_ram32(target, 0x20000000, 0x20000); /* 128kiB DTCM RAM */
-		target_add_ram32(target, 0x20020000, 0x60000); /* 384kiB RAM */
+		uint32_t dtcm_size = 64U * 1024U; /* 64kiB DTCM RAM */
+		uint32_t ahbsram_size = 16U * 1024U;
+		if (target->part_id == ID_STM32F72X) {
+			ahbsram_size = (176U + 16U) * 1024U; /* 192kiB SRAM1/2 */
+		} else if (target->part_id == ID_STM32F74X) {
```
Comment (dragonmux) [inline src/target/stm32f4.c:430]: This is a single statement `if` statement - drop the braces please. Same for the following `else if`.

File: src/target/stm32f4.c [hunk 2]
```diff
@@ -423,9 +423,21 @@ static bool stm32f4_attach(target_s *const target)
...
+			ahbsram_size = (240U + 16U) * 1024U; /* 256kiB SRAM1/2 */
+		} else if (target->part_id == ID_STM32F76X) {
+			dtcm_size = 128U * 1024U;            /* 128kiB DTCM RAM */
+			ahbsram_size = (368U + 16U) * 1024U; /* 384kiB SRAM1/2 */
+		}
+		target_add_ram32(target, 0x00000000, 0x4000); /* 16kiB ITCM RAM */
+		/* On STM32F7, DTCM and AHB SRAM are contiguous */
+		target_add_ram32(target, 0x20000000, dtcm_size);
+		target_add_ram32(target, 0x20000000 + dtcm_size, ahbsram_size);
```
Comment (dragonmux) [inline src/target/stm32f4.c:439]: As you are here working on these, please `U` suffix the addresses and size information and turn them into `#define`'s at the top of file as appropriate.

**Review by dragonmux — COMMENTED** [review]
This is looking good - there are just a couple of formatting things. With them taking care of, we'll happily get this merged for v2.0.0.

File: src/target/stm32f4.c (hunk 2 above)
Comment (ALTracer) [reply src/target/stm32f4.c]: Suffixed base addresses in new/edited code. Hoisted `STM32F7_DTCM_BASE` up top. Ignored 0x0U ITCM RAM base for now (`ITCM_BASE` is for the Flash alias, not RAM), and I'm not sure someone needs an alias for address zero.

Comment (dragonmux) [reply src/target/stm32f4.c]: We do as it has specific meaning and is a valid address in the map - given it's the `ITCM_BASE`, please name it as `STM32F7_ITCM_BASE`.

Comment (ALTracer) [reply src/target/stm32f4.c]: Named it `STM32F7_ITCM_RAM_BASE`, extending the other newly added names as well.

File: src/target/stm32f4.c [hunk 3]
```diff
@@ -99,6 +110,11 @@
 #define AXIM_BASE 0x8000000U
 #define ITCM_BASE 0x0200000U
 
+#define STM32F7_ITCM_RAM_BASE 0x0U
```
Comment (dragonmux) [inline src/target/stm32f4.c:113]: Do note this should really have all 8 digits present for consistency please - we know they're all 0's but this at least makes the constants all follow the same form.

**Review by dragonmux — COMMENTED** [review]
This seems reasonable. We've got just the one review note and then we think this should be good to mark as ready for merge.

File: src/target/stm32f4.c (hunk 3 above)
Comment (ALTracer) [reply src/target/stm32f4.c]: Amended and fast-forwarded.

**Review by dragonmux — APPROVED** [review]
LGTM, merging. Thank you for the contribution!
