### PR TITLE
Fix CMSIS-DAP access to RP2040

### LINKED ISSUE #1370: BMDA: RP2040 does not connect via dap42 (CMSIS-DAP) adapter
Trying to debug a RP2040 MCU with the dap42 debugger, via CMSIS-DAP interface, the SWD scan fails:
```
(gdb) tar ext :2000
Remote debugging using :2000
(gdb) mon s        
Exception: SWDP invalid ACK
SW-DP scan failed!
Failed
```

Problem is with target selection after a forced error, at the end of the [log file](https://github.com/blackmagic-debug/blackmagic/files/10530429/bad2.log):
```
 command: 06 00 04 00 0f 
response: 06 04 00 01 0d 00 00 00 10 00 00 00 05 00 00 00 b1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
dap_mem_read transferred 4 blocks
ap_memread @ e00ffff0 len 16: 0d 00 00 00 10 00 00 00 05 00 00 00 b1 00 00 00
dap_swd_dp_error (protocol recovery? false)
-> dap_swj_sequence (64 cycles)
 command: 12 40 ff ff ff ff ff ff ff 0f 
response: 12 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
 command: 05 00 01 02 
response: 05 01 01 77 24 c1 0b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
        dap_read_reg 00 0bc12477
        dap_write_reg 0c 01002927
 command: 05 00 01 0c 27 29 00 01 
response: 05 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
dap_write_reg 0c data 01002927:fault
 command: 05 00 01 06 
response: 05 00 07 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
```

The code is at cmsis_dap.c, line 282:
```
static uint32_t dap_swd_dp_error(adiv5_debug_port_s *dp, const bool protocol_recovery)
{
	DEBUG_PROBE("dap_swd_dp_error (protocol recovery? %s)\n", protocol_recovery ? "true" : "false");
	if (dp->version >= 2 || protocol_recovery) {
		/* On protocol error target gets deselected.
		 * With DP Change, another target needs selection.
		 * => Reselect with right target! */
		dap_line_reset();
		dap_read_reg(dp, ADIV5_DP_DPIDR);
		dap_write_reg(dp, ADIV5_DP_TARGETSEL, dp->targetsel);
		/* Exception here is unexpected, so do not catch */
	}
```

The line with `dap_write_reg(dp, ADIV5_DP_TARGETSEL, dp->targetsel);` fails, as the probe returns error 7 = NO_ACK (no response from target). Note that from the reset all read and write commands fail.

Any ideas?

### PR DESCRIPTION
**Pull request by dmsc**
## Detailed description

This fixes #1370:

- Fixes attaching to multi-drop targets by using correct write sequence.
- Fixes memory reading, allowing to correctly decode ROM tables.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

fixes #1370

### CODE REVIEW

File: src/platforms/hosted/cmsis_dap.c [hunk 1]
```diff
@@ -292,7 +295,7 @@ static uint32_t dap_swd_dp_error(adiv5_debug_port_s *dp, const bool protocol_rec
 		 */
 		dap_line_reset();
 		if (dp->version >= 2)
-			dap_write_reg_no_check(dp, ADIV5_DP_TARGETSEL, dp->targetsel);
+			dap_dp_low_write(dp, ADIV5_DP_TARGETSEL, dp->targetsel);
```
Comment (dragonmux) [inline src/platforms/hosted/cmsis_dap.c:298]: Given this change and that this is the only location dap_write_reg_no_check() is called (we couldn't find this variant of low-level write when making that change) please remove dap_write_reg_no_check() from the dap.h header and dap.c source file)

File: src/platforms/hosted/cmsis_dap.c [hunk 2]
```diff
@@ -87,6 +87,9 @@ typedef enum cmsis_type {
 typedef struct hid_device_info hid_device_info_s;
 #endif
 
+/*- Forward declaration -----------------------------------------------------*/
```
Comment (dragonmux) [inline src/platforms/hosted/cmsis_dap.c:90]: Drop the comment, it's not adding anything (this file still needs style fixes). Also drop the `const` marking on the data parameter in this declaration (clang-tidy lint)

**Review by dragonmux — CHANGES_REQUESTED** [review]
Couple of reasonably simple items to address prior to merge. Good job figuring out the fixes for this! With the review items fixed, we're happy to merge this

File: src/platforms/hosted/cmsis_dap.c (hunk 1 above)
Comment (dmsc) [reply src/platforms/hosted/cmsis_dap.c:297]: done!

File: src/platforms/hosted/cmsis_dap.c (hunk 2 above)
Comment (dmsc) [reply src/platforms/hosted/cmsis_dap.c]: Done. I did not modify the actual implementation, to minimize the diff.

**Comment by dmsc** [comment]
> LGTM, merging!

Thank you!
