### PR TITLE
Fix: Cortex-M SWD attach regression

### LINKED ISSUE #1319: S32K148: Device fails to attach
With `Black Magic Probev1.9.0-rc0-3-gd5e59b94, Hardware Version 6`, the S32K simply fails to attach. It scans just fine, but attaching does not work anymore.

```
(gdb) mon ver
Black Magic Probev1.9.0-rc0-3-gd5e59b94, Hardware Version 6
Copyright (C) 2022 Black Magic Debug Project
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

(gdb) mon s
Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      S32K14x M4
 2      Kinetis Recovery (MDM-AP)
(gdb) att 1
Attaching to Remote target
Attaching to Remote target failed
(gdb) mon s
Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      S32K14x M4
 2      Kinetis Recovery (MDM-AP)
(gdb) att 1
Attaching to Remote target
Attaching to Remote target failed
(gdb) att 2
Attaching to Remote target
Attaching to Remote target failed
(gdb)
```

Loading an older version fixes things.

```
(gdb) tar ext \\.\COM5
Already connected to a remote target.  Disconnect? (y or n) y
Remote debugging using \\.\COM5
(gdb) mon s
Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      S32K14x M4
 2      Kinetis Recovery (MDM-AP)
(gdb) att 1
Attaching to Remote target
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x000182d2 in ?? ()
(gdb) mon ver
Black Magic Probe v1.8.0-682-g12bda1e0, Hardware Version 6
Copyright (C) 2022 Black Magic Debug Project
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

(gdb)
```

### PR DESCRIPTION
**Pull request by dragonmux**
## Detailed description

This PR addresses the issue reported in https://github.com/blackmagic-debug/blackmagic/issues/1319 and on Discord where a user trying to attach to various Cortex-M cores via SWD would get an attach failure from the firmware, the remote protocol going non-responsive (BMDA connected to BMF), or have the debug server abort (BMDA via ST-Link, JLink, CMSIS-DAP). This would happen only if there was a delay between scan and attach.

The underlying issue causing this (something happening on the bus that causes the target to go into the protocol error state defined by ADIv5.2 §B1.2 subtitle "Protocol errors (SW-DP only)", and §B4.2.5) remains unchanged, however this PR gives BMP proper handling for the no-response answer used to indicate this state and a proper error recovery mechanism which means the target ends up happily back in a usable state and we continue on successfully as before.

A follow-up PR for v1.10 will be needed to address this underlying issue.

Tested on native hardware against STM32F4, Tiva-C and other targets. Tested via BMDA using the BMP remote protocol, ST-Link and CMSIS-DAP.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #1319

### CODE REVIEW

File: src/platforms/hosted/dap.c [hunk 1]
```diff
@@ -583,40 +594,41 @@ void dap_ap_write(adiv5_access_port_s *ap, uint16_t addr, uint32_t value)
...
+	mem_access_setup(ap, requests, src, align);
+	requests[3].request = SWD_AP_DRW | DAP_TRANSFER_RnW;
+	requests[4].request = SWD_DP_R_RDBUFF | DAP_TRANSFER_RnW;
+	uint32_t result[2];
+	if (!perform_dap_transfer(ap->dp, requests, 5U, result, 2U)) {
+		DEBUG_WARN("dap_read_single failed\n");
+		memset(dest, 0, sizeof(uint32_t));
+		return;
+	}
+	/* Pull out the data from the *second* response (value of RDBUFF) */
```
Comment (zyp) [inline src/platforms/hosted/dap.c:566]: This is incorrect. CMSIS-DAP handles the AP read latency on the probe side and does an implicit read of RDBUFF, so the host should never need to read it explicitly. The actual read value ends up in the first response slot, and the second contains undefined garbage (all zeroes in my testing). The proper solution here is to simply remove the fifth transfer request and return the first response.

File: src/platforms/hosted/cmsis_dap.c [hunk 2]
```diff
@@ -425,33 +425,34 @@ static void dap_mem_read(adiv5_access_port_s *ap, void *dest, uint32_t src, size
...
-		unsigned int blocksize = (src | 0x3ffU) - src + 1U;
-		if (blocksize > len)
-			blocksize = len;
-		while (blocksize) {
-			unsigned int transfersize = blocksize;
-			if (transfersize > max_size)
-				transfersize = max_size;
-			if (!dap_read_block(ap, dest, src, transfersize, align)) {
+	/* Otherwise proceed blockwise */
+	dap_ap_mem_access_setup(ap, src, align);
```
Comment (zyp) [inline src/platforms/hosted/cmsis_dap.c:459]: This needs to be called inside the loop with `src + offset` to update AP_TAR at 1024B boundaries, otherwise it'll wrap.

File: src/platforms/hosted/cmsis_dap.c [hunk 3]
```diff
@@ -454,34 +454,37 @@ static void dap_mem_write_sized(adiv5_access_port_s *ap, uint32_t dest, const vo
...
-			blocksize = len;
-		while (blocksize) {
-			unsigned int transfersize = blocksize;
-			if (transfersize > max_size)
-				transfersize = max_size;
-			if (!dap_write_block(ap, dest, src, transfersize, align)) {
-				DEBUG_WARN("mem_write failed %u\n", ap->dp->fault);
-				ap->dp->fault = 1;
+	/* Otherwise proceed blockwise */
+	dap_ap_mem_access_setup(ap, dest, align);
```
Comment (zyp) [inline src/platforms/hosted/cmsis_dap.c:493]: This needs to be called inside the loop with `dest + offset` to update AP_TAR at 1024B boundaries, otherwise it'll wrap.

File: src/platforms/hosted/dap.c (hunk 1 above)
Comment (dragonmux) [reply src/platforms/hosted/dap.c]: Many thanks for the extra information, this should now be fixed

File: src/platforms/hosted/cmsis_dap.c (hunk 2 above)
Comment (dragonmux) [reply src/platforms/hosted/cmsis_dap.c]: This should now be fixed - many thanks :)

File: src/platforms/hosted/cmsis_dap.c (hunk 3 above)
Comment (dragonmux) [reply src/platforms/hosted/cmsis_dap.c]: This should now be fixed - many thanks :)

**Review by esden — APPROVED** [review]
LGTM
