### PR TITLE
Fix: Ensure F-packet replies from gdb are reliably detected

### LINKED ISSUE #1845: Semihost: regression from v1.9.3 to aa67538
One of my semihost on-target tests is failing when updating the BlackMagicProbe firmware from v1.9.3 to the latest aa6753833764b41697900536395bb343f611377d in main.

The issue arises when I try to write a negative value through semihost:

```cpp
auto val = semihost_persistence::add("./logs/test_add", -3);
zassert_equal(-3, val.value());
```

(`semihost_persistence::add` will rely on both read as well as write calls)

The debugger will hang in the following manner:

image

Positive values work in both versions.

This is using SAMC21.

### PR DESCRIPTION
**Pull request by TechnoMancer**
## Detailed description

* This fixes an issue.
* The origin of the issue was the change contributed in #1686 which added the loop in semihosting_get_gdb_response.
* The check for an F-packet reply was too late as gdb_main_loop may have already clobbered the packet by the time this is checked.

Collaborative inspection of debug logs from #1845 and provided by others pointed to inconsistent behaviour dealing with remote file i/o completion, which was narrowed down to the F-packet reply check being done after the packet had been processed and the packet buffer possibly clobbered.

This is corrected by checking if the received packet is an F-packet first then processing it and using the result of the check to exit the loop after the processing.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (see [Building the firmware](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-firmware))
* [x] It builds as BMDA (see [Building the BMDA](https://github.com/blackmagic-debug/blackmagic?tab=readme-ov-file#building-black-magic-debug-app))
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #1845.

### CODE REVIEW

File: src/target/semihosting.c [hunk 1]
```diff
@@ -183,9 +183,12 @@ static int32_t semihosting_get_gdb_response(target_controller_s *const tc)
 		/* If this was an escape packet (or gdb_if reports link closed), fail the call */
 		if (size == 1U && packet_buffer[0] == '\x04')
 			return -1;
+		/* If this was an F-packet, we are done waiting.
```
Comment (dragonmux) [inline src/target/semihosting.c:186]: As this is going to be a multi-line comment, please use the style
```c
/*
 * Multi-line
 * comment
 */
```

**Review by dragonmux — CHANGES_REQUESTED** [review]
There's one small stylistic change, but with that taken care of, we'll be happy to merge this.

Many thanks to you and ALTracer for this fix even if he had to pull his PR for geopolitical reasons.

**Review by dragonmux — APPROVED** [review]
LGTM, thank you for the contribution! Merging.
