### PR TITLE
stm32wlxx: CPU2 needs wake-up call and has unexpected PIDR4 in AP1

### LINKED ISSUE #832: Add support for STM32WLE5JC SOC (Cortex M4 + Lora radio)
Hi all, 

I'd like to use BMP for flashing/debugging new STM32WLE5 chips.  

https://www.st.com/en/microcontrollers-microprocessors/stm32wle5jc.html

I have Seeed Studio Lora E5 module on a DIY breakboard, which exposes SWDIO/SWCLK/RST pins: 

</img>

With BMP hosted ( blackmagic -t -v31), I could get traces with Read Timeout errors:  

```
CPUID 0x410fc241 (M4 var 0 rev 1)
!HM000023000040e000ed8800000004#
Timeout on read RESP
remote_ap_mem_read error -4 around 0xe000ed88
ap_memread @ e000ed88 len 4: 05 56 00 00
ap_mem_write_sized @ e000ed88 len 4, align 4: 05 56 f0 00
!Hm00002300004002e000ed88000000040556f000#
Timeout on read RESP
remote_ap_mem_write_sized error -4 around address 0xe000ed8c
!HM000023000040e000ed8800000004#
Timeout on read RESP
remote_ap_mem_read error -4 around 0xe000ed88
ap_memread @ e000ed88 len 4: 05 56 00 00
!HM000023000040e000ed7c00000004#
Timeout on read RESP
remote_ap_mem_read error -4 around 0xe000ed7c
ap_memread @ e000ed7c len 4: 05 56 00 00
swdptap_seq_out         8 ticks: 0000008d
```

As CPACR (FPU access register) is located at address 0xE000ED88, I tried to remove the FP probe code in cortexm.c
(Search for /* Probe for FP extension */ in the source)

It seems I can go further with this hack, but I still have errors: 

```
Read  AP 0x01 CSW   : 0x0100001a
!Ha000001f4#
Timeout on read RESP
Read  AP 0x01 CFG   : 0x0100001a
AP   0: IDR=00370011 CFG=0100001a BASE=0100001a CSW=01000008
AP#0 IDR = 0x00370011 (AHB-AP var1 rev0)
!HM00000100000801000ff000000004#
Timeout on read RESP
remote_ap_mem_read error -4 around 0x01000ff0
ap_memread @ 1000ff0 len 4: 00 00 00 00
!HM00000100000801000ff400000004#
Timeout on read RESP
remote_ap_mem_read error -4 around 0x01000ff4
ap_memread @ 1000ff4 len 4: 00 00 00 00
```
Now I need help to verify if ADIv5 driver tries to read correct addresses, and try to understand why these reads ends up with Timeout errors. 

At the same time, I'll continue the analysis this way:
I'll record a working SWD sessions with openocd + Logic Analyzer SWD Decoder, and try to compare with faulty BMP transactions.

I don't have much knowledge about Arm Debug Interface, so any help is welcome . 

Thanks 

Olivier

### PR DESCRIPTION
**Pull request by UweBonnes**
STM32WLE still sees AP1 but on first scan aborts gracefully after some errors
and on later runs sees AP1 as unusable. Fixes #832.

### CODE REVIEW

**Comment by dragonmux** [comment]
Hi Uwe,
Thank you for linking the associated issue. However..

The description you've given for the PR doesn't give us any useful information on what you've changed or why that doesn't require some deep knowledge of the target that we don't have. Please edit the description to explain what you've done here better so we can review this for merge.

It would be ideal if you could even include some console output showing what a user would have seen before and what they see after in case this ever regresses.

Thanks for the contribution!

**Comment by UweBonnes** [comment]
Before:
> ./blackmagic -t -C
Black Magic Debug App v1.8.0-82-g14d38466
 for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, JLink and libftdi/MPSSE
Using 1d50:6018 7KJN7JK8 Black Magic Debug
 Black Magic Probe  v1.8.0-82-g14d38466
...
ROM: Table END
AP   1: IDR=84770001 CFG=00000000 BASE=f0000003 CSW=43800040 (AHB-AP var0 rev8
remote_ap_mem_read returned REMOTE_RESP_ERR at apsel 1, addr: 0xf0000ff0
Timeout on read RESP
remote_ap_mem_read error -4 around 0xf0000ff4
... more errors until BMD hangs up and needs replug
After:
> ./blackmagic -t -C
Black Magic Debug App v1.8.0-83-g4df7ba7e
 for Black Magic Probe, ST-Link v2 and v3, CMSIS-DAP, JLink and libftdi/MPSSE
Using 1d50:6018 7KJN7JK8 Black Magic Debug
 Black Magic Probe  v1.8.0-82-g14d38466
...
AP   1: IDR=84770001 CFG=00000000 BASE=f0000003 CSW=43800040 (AHB-AP var0 rev8
ROM: Table BASE=0xf0000000 SYSMEM=0x00000001, designer 420 Partno 497
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer 43b Partno 4c0
 0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008  DEVTYPE = 0x00 ARCHID = 0x0000) -> cortexm_probe
CPUID 0x410cc601 (M0+ var 0 rev 1)
 1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a  DEVTYPE = 0x00 ARCHID = 0x0000)
 2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b  DEVTYPE = 0x00 ARCHID = 0x0000)
 ROM: Table END
 0xf0001000: Debug component - Unknown (PIDR = 0x04000bb9a6 DEVTYPE = 0x14 ARCHID = 0x1a14)
2 Entry 0x2002 -> Not present
3 Entry 0x10000002 -> Not present
ROM: Table END
***  1      STM32WLxx M4
***  2      STM32WLxx M0+
RAM   Start: 0x10000000 length = 0x8000
RAM   Start: 0x20000000 length = 0x10000
Flash Start: 0x08000000 length = 0x40000 blocksize 0x800

File: src/target/adiv5.h [hunk 1]
```diff
@@ -95,6 +95,14 @@
 #define AP_DESIGNER_TEXAS        0x017
 #define AP_DESIGNER_ATMEL        0x01f
 #define AP_DESIGNER_STM          0x020
+/* CPU2 for STM32W(L|B) uses ARM JEDEC continuation (4) and
+ * not STM ARM JEDEC continuation (0) as for CPU1.
+ * See RM0453:
```
Comment (dragonmux) [inline src/target/adiv5.h:100]: what does "RM0453" refer to (could this be made into a link to the appropriate document?)

**Review by dragonmux — CHANGES_REQUESTED** [review]
We found only one thing that could do with improving before merge. LGTM otherwise.

**Comment by UweBonnes** [comment]
rm0xxx are the reference manuls for STM devices.  These reference manuals are mentioned in many places in the target/stm32 files w/o explicit link. 
> rg -i rm0 | wc
     79     699    5501
Anybody working on register level with stm32 devices uses these manuals to understand what is going on.

**Comment by dragonmux** [comment]
We understand that right now, but.. in the interests of a new user who doesn't know where to find them, or even us in 6 months time.. please provide a link to the correct manual in the patch set.

As we find instances of reference manuals being talked about by the code, we're fixing them up to include a link to that manual for better future proofing.

**Comment by UweBonnes** [comment]
STM has the bad habit of changing links like underpants. I.m.h.o., googling "stm32 rm0434" is a better way to find these documents than to 404 links. The product page on st.com for the device also will have the actual link.

**Comment by dragonmux** [comment]
In that case, please provide a link and clarify that you're definitely referring to ST's RM0434 and not another vendor's reference manuals.

Not all code in the stm32*.c files refers to ST products, making references like these ambiguous which is what we're trying to fix and eliminate issues with.

File: src/target/adiv5.c [hunk 2]
```diff
@@ -294,9 +295,10 @@ static uint32_t adiv5_mem_read32(ADIv5_AP_t *ap, uint32_t addr)
 static uint32_t adiv5_ap_read_id(ADIv5_AP_t *ap, uint32_t addr)
 {
 	uint32_t res = 0;
+	uint8_t data[16];
```
Comment (dragonmux) [inline src/target/adiv5.c:298]: We're unsure with the merits and drawbacks of this change - could you put that in a separate PR as it needs some stringent testing etc and we'd like to merge the rest of the changeset.

File: src/target/adiv5.c [hunk 3]
```diff
@@ -294,9 +295,10 @@ static uint32_t adiv5_mem_read32(ADIv5_AP_t *ap, uint32_t addr)
...
+	adiv5_mem_read(ap, data, addr, sizeof(data));
 	for (int i = 0; i < 4; i++) {
-		uint32_t x = adiv5_mem_read32(ap, addr + 4 * i);
-		res |= (x & 0xff) << (i * 8);
+		res |= (data[4 * i] << (i * 8));
```
Comment (dragonmux) [inline src/target/adiv5.c:301]: The extra ()'s around the outside of the operation are redundant and suppress warnings, please leave them out - ie `res |= data[i * 4U] << (i * 8U);`

**Review by dragonmux — COMMENTED** [review]
This is looking better, but you introduced further changes which unfortunately require additional testing before they could be merged - please put the extra ADIv5 changes in a separate PR

**Comment by dragonmux** [comment]
We finally found your reasoning for the ADIv5 change.. next time please put that in the PR as it's not very discoverable in the commit message body. We have poor insight into information you squirrel there.

We'll have to test this change with a bunch of hardware and only if it doesn't regress other devices will we merge. We otherwise approve this for merge save for the single noted change.

**Review by dragonmux — APPROVED** [review]

**Comment by dragonmux** [comment]
Tested ok with the targets we have
