### PR TITLE
target: GigaDevice GD32E50x

### LINKED ISSUE #1426: New target: GD32E50x
## Summary
Add basic support for GigaDevices GD32E50x Cortex-M33 chips.
## Impact
stm32f1 flash code, cortex-m generic detection code
## Description
I was searching for ways to debug a custom board with a GD32E508Z. OpenOCD didn't merge this patch https://review.openocd.org/c/openocd/+/6794 upstream yet, so I applied it locally over 0.12.0 and recompiled. 
Tested adapters:
* STLINK/V2 standalone seemed to work with OpenOCD both in HLA and DAP modes, albeit it only supports SWD, not JTAG mode. st-util and friends from https://github.com/stlink-org/stlink think this is a STM32F03 (flash?) chip.
* JLink V5 IAR-KS 2008 supports only JTAG mode, and fails enumeration with this board. It works with a different board and different Cortex-M chip, maybe PCB issue. I checked the pull-ups and pull-downs (4.7k) for all JTAG lines as well as target pins.
* JLink V8 2014 supports both JTAG and SWD, but fails JTAG (`Could not measure total IR len. TDO is constant high.`). In SWD it sees a Cortex-M33 and then complains that "your JLink hardware does not support ARMv8-M target debugging". OpenOCD works though.
* WeActStudio MiniF4 rev 3.1 flashed with BlackMagic Probe 1.9.0 manually compiled firmware detects the chip, but doesn't know what to do with it (no target support). I then ported the changes from OpenOCD code to BMP target support code (ID, detection, probing) and now I can attach, single-step, use hardware breakpoints, load flash and mass-erase the target chip in SWD mode. JTAG doesn't work, might be a blackpillv2 platform issue (collision between TDI pin and LED).

I don't have access to any other GD32 chips and can't verify impact. I do have a few personal boards, precisely: an original bluepill 128k (STM32F103CBT6), a second blackpill with STM32F411CEU6, and a couple original Pico rp2040 boards for Rust-DAP firmware to use in CMSIS-DAP mode or as logic analyzers etc. There are some Discovery boards which I could reflash to JLink-OB if needed.

<details>
  <summary>JLinkExe output on V8 adapter:</summary>

```
Connecting to target via SWD                               
Found SW-DP with ID 0x0BE12477                             
DPv0 detected                                              
CoreSight SoC-400 or earlier
Scanning AP map to find all available APs                  
AP[1]: Stopped AP scan as end of AP map has been reached   
AP[0]: AHB-AP (IDR: 0x14770015)                            
Iterating through AP map to find AHB-AP to use                                                                        
AP[0]: Core found                                          
AP[0]: AHB-AP ROM base: 0xE00FE000                       
CPUID register: 0x410FD214. Implementer code: 0x41 (ARM)   
Feature set: Mainline                                      
Cache: No cache              
Found Cortex-M33 r0p4, Little endian.                      
                                                                                                                      
****** Error: Specific core setup failed.
```
</details>

### PR DESCRIPTION
**Pull request by ALTracer**
Add basic support for GigaDevices GD32E50x Cortex-M33 chips.

## Detailed description
GigaDevice GD32E50x are Cortex-M33 cores with STM32F1-style peripherals. 
Per the "User Manual", flash is in 8KiB pages; 
and `DBGMCU_BASE=0xE0044000`, unlike on other chips.

This chip is not detected by BMP yet. 
Upon testing locally both with `blackpill-f411ce` platform and BMDA working via WeAct CMSIS-DAP / the blackpill BMP, the chip is detected via SWD, is flashable and debuggable (gdb hbreak, load, cont/Ctrl+C etc.)

See #1426 for more information.

PC 1: Linux Mint 21 (Ubuntu focal) with `gcc-arm-none-eabi` 10.3, newlib-3.3.0 and gdb-multiarch. Flash & debug tested.
PC 2: Gentoo 2.13 stable amd64/17.1 with `cross-arm-none-eabi/gcc:12.2.1` and newlib-4.3.0. Build tested.

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

fixes #1426

### CODE REVIEW

File: src/target/stm32f1.c [hunk 1]
```diff
@@ -128,13 +129,21 @@ static uint16_t stm32f1_read_idcode(target_s *const target)
 {
 	if ((target->cpuid & CPUID_PARTNO_MASK) == CORTEX_M0 || (target->cpuid & CPUID_PARTNO_MASK) == CORTEX_M23)
 		return target_mem_read32(target, DBGMCU_IDCODE_F0) & 0xfffU;
+
```
Comment (dragonmux) [inline src/target/stm32f1.c:132]: Please remove this extra newline

File: src/target/stm32f1.c [hunk 2]
```diff
@@ -128,13 +129,21 @@ static uint16_t stm32f1_read_idcode(target_s *const target)
...
+		return target_mem_read32(target, DBGMCU_IDCODE_GD32E5) & 0xfffU;
+
 	return target_mem_read32(target, DBGMCU_IDCODE) & 0xfffU;
 }
 
 /* Identify GD32F1, GD32F2 and GD32F3 chips */
 bool gd32f1_probe(target_s *target)
 {
 	const uint16_t device_id = stm32f1_read_idcode(target);
+
```
Comment (dragonmux) [inline src/target/stm32f1.c:144]: Please remove this extra newline

File: src/target/stm32f1.c [hunk 3]
```diff
@@ -151,7 +160,21 @@ bool gd32f1_probe(target_s *target)
...
+#if 0
+		/* If stm32f1_read_idcode() is not patchable for M33, then we'll do it here */
+		if ((target->cpuid & CPUID_PARTNO_MASK) == CORTEX_M33) {
+			const uint16_t device_id2 = target_mem_read32(target, DBGMCU_IDCODE_GD32E5) & 0xfffU;
+			if (device_id2 == 0x444U) {
+				target->driver = "GD32E5";
+				break;
+			}
+		}
+#endif
```
Comment (dragonmux) [inline src/target/stm32f1.c:177]: Please remove this `#if 0` in favour of the change to the ID Code read function

File: src/target/stm32f1.c [hunk 4]
```diff
@@ -94,6 +94,7 @@ static bool stm32f1_mass_erase(target_s *target);
 
 #define DBGMCU_IDCODE    0xe0042000U
 #define DBGMCU_IDCODE_F0 0x40015800U
```
Comment (dragonmux) [inline src/target/stm32f1.c:96]: These need re-formatting so the `0x` of the constants align with the start of the `DBGMCU_IDCODE_GD32E5` one (use spaces, or run clang-format on this one file)

**Review by dragonmux — CHANGES_REQUESTED** [review]
Thank you very much for the contribution! The only review items we can see are some extra whitespace, the clang-format lint on the DBGMCU_IDCODE macro definitions, and a `#if 0` that needs to go - after that, this looks ready to merge.

File: src/target/stm32f1.c (hunk 4 above)
Comment (ALTracer) [reply src/target/stm32f1.c:96]: If you approve of the macro name, then I'll align (touch adjacent lines) with spaces like clang-format-15 suggests.

Comment (dragonmux) [reply src/target/stm32f1.c:96]: We do, the macro name seems good

File: src/target/stm32f1.c (hunk 3 above)
Comment (ALTracer) [reply src/target/stm32f1.c:177]: Okay. This was my initial version, as I wasn't sure if I was allowed to touch generic `stm32f1_read_idcode()`. I cannot test breakage for other targets this might introduce, however, the only M33's I know are not using ancient stm32f1 flash peripherals.

Comment (dragonmux) [reply src/target/stm32f1.c:177]: That's absolutely fine, We'd prefer to build a set of comprehensive rules in stm32f1_read_idcode() which we refactored out for this exact cause and reason, than having ad-hoc readouts of the DBGMCU ID Code information

**Review by dragonmux — APPROVED** [review]

**Comment by dragonmux** [comment]
Looks good! If you're happy that you don't need an extra `PROBE(gd32f1_probe)` call in cortexm.c then we're happy to merge this once the builds complete
